=== Daniyar624/thirdTask/src/resources/knifeShopSchemaDesign.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="knife_shop">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element name="knife" maxOccurs="unbounded">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element ref="name"/>
                            <xs:element ref="type"/>
                            <xs:element ref="handy"/>
                            <xs:element ref="origin"/>
                            <xs:element ref="visual_parameters"/>
                            <xs:element ref="value"/>
                        </xs:sequence>
                        <xs:attribute name="id" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- definition of simple elements -->
    <xs:element name="name">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[a-zA-Z]+"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="type">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="knife"/>
                <xs:enumeration value="dagger"/>
                <xs:enumeration value="sword"/>
                <xs:enumeration value="ax"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="handy">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="one-handed|two-handed"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="origin">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[a-zA-Z]+"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="length">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="10"/>
                <xs:maxExclusive value="300"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="width">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="10"/>
                <xs:maxInclusive value="300"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="material">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[a-zA-Z]+"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="handle">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="plastic"/>
                <xs:enumeration value="metal"/>
                <xs:enumeration value="wood"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="bloodstream_presence">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="Yes|No"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="value">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="collectible|non-collectible"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <!-- definition of complex elements -->
    <xs:element name="visual_parameters">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="length"/>
            <xs:element ref="width"/>
            <xs:element ref="material"/>
            <xs:element ref="handle"/>
            <xs:element ref="bloodstream_presence"/>
        </xs:sequence>
    </xs:complexType>
    </xs:element>



</xs:schema>

=== Daniyar624/thirdTask/src/resources/knifeShop.xml
<?xml version="1.0" encoding="UTF-8"?>
<knife_shop> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="$LOCAL_SCHEMA$"
            xsi:noNamespaceSchemaLocation="knifeShopSchemaDesign.xsd">


    <knife id="6">
        <name>Shadowmourne</name>
        <type>ax</type>
        <handy>two-handed</handy>
        <origin>Azeroth</origin>
        <visual_parameters>
            <length>55</length>
            <width>300</width>
            <material>steel</material>
            <handle>wood</handle>
            <bloodstream_presence>Yes</bloodstream_presence>
        </visual_parameters>
        <value>collectible</value>
    </knife>

    <knife id="4">
        <name>DaggerBlast</name>
        <type>dagger</type>
        <handy>one-handed</handy>
        <origin>Kazakhstan</origin>
        <visual_parameters>
            <length>20</length>
            <width>28</width>
            <material>bronze</material>
            <handle>plastic</handle>
            <bloodstream_presence>No</bloodstream_presence>
        </visual_parameters>
        <value>non-collectible</value>
    </knife>

    <knife id="71">
        <name>DickJohn</name>
        <type>dagger</type>
        <handy>one-handed</handy>
        <origin>America</origin>
        <visual_parameters>
            <length>60</length>
            <width>75</width>
            <material>gold</material>
            <handle>wood</handle>
            <bloodstream_presence>No</bloodstream_presence>
        </visual_parameters>
        <value>collectible</value>
    </knife>

    <knife id="2">
        <name>Tesak</name>
        <type>sword</type>
        <handy>one-handed</handy>
        <origin>Kazakhstan</origin>
        <visual_parameters>
            <length>20</length>
            <width>28</width>
            <material>steel</material>
            <handle>metal</handle>
            <bloodstream_presence>Yes</bloodstream_presence>
        </visual_parameters>
        <value>non-collectible</value>
    </knife>


</knife_shop>
